### PR TITLE
Lj 99 pond addlink

### PR DESCRIPTION
**Pull request by krischarbonneau**
# Description

[LJ-99 Remove the "explore this journey" link and make the box clickable instead](https://lj-decd.atlassian.net/browse/LJ-99?atlOrigin=eyJpIjoiZjA0ZjUzM2ZkMzkyNGJkNzg5MTYyNDA0ZmM3NjYyOGQiLCJwIjoiaiJ9 )

Opening this back up to get discussion on it. Made a couple changes based on @pcraig3 suggestions. Added underline to the title on hover, changed the text back to normal, removed border from subtopics and made them solid color as well (suggestions on if this color is good or not?).

## Test Instructions

1. Pull in branch
2. Type ```npm run dev``` 

## Meets Definition of Done

- [ ] Meets design spec
- [ ] unit tests are included

### CODE REVIEW

**Comment by pcraig3** [comment]
Hey Kris, I have some more feedback, but I just took a screenshot of it.

Screen Shot 2021-05-11 at 14 11 20

For the bottom padding/margin, we could do `mb-2` or `mb-3`.

**Comment by krischarbonneau** [comment]
> Hey Kris, I have some more feedback, but I just took a screenshot of it.
> 
> Screen Shot 2021-05-11 at 14 11 20
> 
> For the bottom padding/margin under the second heading, we could do `mb-2` or `mb-3`.

Changed the line height of the title, changed margins as per your pic, got rid of the uppercase and bold. Can't really do much about the full width (tried a few things to get rid of the whitespace from flex-wrap to no avail).

I made the icon more responsive so it's not randomly huge or off center at different resolutions anymore. 
Let me know if you have any other suggestions!

**Comment by pcraig3** [comment]
> Can't really do much about the full width (tried a few things to get rid of the whitespace from flex-wrap to no avail). 

Sorry, should have explained that better. I meant that I didn't think the grey "tags" should be full width, especially when they were only a short word. 

image

(eg, lots of grey we don't need there)

What you've done now looks fine. 

But we shouldn't mess with the layout container. Let's revert that one. It makes the page weirdly thin on mobile and it also seems to mean there's tons of whitespace under the boxes (before the "report a problem" link — see gif below). Happy to just take the other improvements you have so far and then we can do the width / mobile stuff separately.

Screen Recording 2021-05-13 at 16 28 16

**Review by MarcoGoC — APPROVED** [review]
Looks good to me, for another PR i thought we were going to change from 3 per row to 2 per row to 1 per row, according to space available, instead of from 3 to 1.

**Review by pcraig3 — APPROVED** [review]
Thanks @krischarbonneau, it's a big improvement!

**Pull request merged**
