### PR TITLE
Added search bar component, styling

### PR DESCRIPTION
**Pull request by krischarbonneau**
# Description

[LJ-41 Search Bar](https://lj-decd.atlassian.net/browse/LJ-41?atlOrigin=eyJpIjoiNDQxZWI3ZDU0ZmIzNDYzNjliM2ZiZGUxOWZiYmNiZDEiLCJwIjoiaiJ9)

Added search bar component based on what was already created for Alpha Site. Changed global css and tailwind config to match Alpha Site since they are related (it's really close to having Canada.ca typography set up but I'll finish that up in a different PR during the next sprint).

Screenshot 2021-04-12 165951

## Test Instructions

1. Import Search Bar component
2. Put search bar component in header with specified placeholder text.

## Meets Definition of Done

- [☑] We have a search bar component we can import into another page, but it’s not yet imported.

### CODE REVIEW

**Comment by pcraig3** [comment]
I know we don't really have a place to put the search bar yet, but can you post a screenshot of the search bar so we can see it?

**Comment by krischarbonneau** [comment]
> I know we don't really have a place to put the search bar yet, but can you post a screenshot of the search bar so we can see it?

Absolutely. Updated my original comment with a screenshot

**Review by pcraig3 — APPROVED** [review]
Okay, let's merge.

**Review by MarcoGoC — APPROVED** [review]
Looks good works well,

**Pull request merged**
